name: SuperSkyMobs
main: com.maxengine.superskymobs.SuperSkyMobsPlugin
version: 1.0.0
api-version: '1.17'
description: Give mobs random equipment in the skyblock world
author: MaxEngine
commands:
  superskymobs:
    description: Main command for SuperSkyMobs
    usage: /superskymobs reload
    permission: superskymobs.commands.reload
permissions:
  superskymobs.commands.reload:
    description: Permission to reload the plugin configuration
    default: op
