name: SuperSkyMobs
main: com.maxengine.superskymobs.SuperSkyMobsPlugin
description: Spawn entities with random armour!
author: MaxEngine
version: 1.1.0
api-version: 1.21

commands:
  superskymobs:
    aliases: [sky]
    description: reload command
    permission: superskymobs.commands.reload
